version: 2
registries:
  familie-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/familie-felles
    username: x-access-token
    password: "${{secrets.READER_TOKEN}}"

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - familie-felles
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
