apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  envFrom:
    - secret: familie-ks-sak
    - secret: familie-ks-sak-unleash-api-token
  image: {{image}}
  port: 8083
  leaderElection: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-4-3840
        name: familie-ks-sak
        autoBackupHour: 2
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-ks-sak
            envVarPrefix: DB
        flags:
          - name: cloudsql.enable_pgaudit
            value: "on"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # Prosessering
          - id: "54cd86b8-2e23-48b2-8852-b05b5827bb0f"  # VEILEDER_ROLLE
          - id: "e40090eb-c2fb-400e-b412-e9084019a73b"  # SAKSBEHANDLER_ROLLE
          - id: "4e7f23d9-5db1-45c0-acec-89c86a9ec678"  # BESLUTTER_ROLLE
          - id: "024bfb25-ead3-4c04-bbe1-1db3d3362188"  # teamfamilie-baks-forvaltning
      replyURLs:
        - "https://familie-ks-sak.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak-frontend
          cluster: prod-gcp
        - application: familie-prosessering
          cluster: prod-gcp
        - application: familie-klage
          cluster: prod-gcp
        - application: bidrag-grunnlag-feature
          namespace: bidrag
          cluster: prod-gcp
        - application: bidrag-grunnlag
          namespace: bidrag
          cluster: prod-gcp
        - application: familie-ef-sak
          cluster: prod-gcp
        - application: familie-baks-mottak
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-brev
          cluster: prod-gcp
        - application: familie-integrasjoner
          cluster: prod-fss
        - application: familie-ks-infotrygd
          cluster: prod-fss
        - application: familie-ef-sak
          cluster: prod-gcp
        - application: familie-tilbake
          cluster: prod-gcp
        - application: tilbakekreving-backend
          namespace: tilbake
          cluster: prod-gcp
        - application: familie-oppdrag
          cluster: prod-fss
        - application: familie-klage
          cluster: prod-gcp
        - application: familie-baks-mottak
          cluster: prod-gcp
        - application: logging
          namespace: nais-system
      external:
        - host: nav-prod-kafka-nav-prod.aivencloud.com
        - host: xsrv1mh6.api.sanity.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-ks-infotrygd.prod-fss-pub.nais.io
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: data-api.ecb.europa.eu
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
        - host: graph.microsoft.com
          ports:
            - port: 443
          # Sanity IPs https://www.sanity.io/docs/api-cdn#5fa01dfe1285 (Fjernes når feilen er rettet av platform teamet https://nav-it.slack.com/archives/C5KUST8N6/p1719994144462539)
        - ipv4: 35.241.31.122
        - ipv4: 35.190.70.79
        - ipv4: 35.186.208.30
        - ipv4: 34.102.229.159
        - ipv4: 34.102.211.197
        - ipv4: 34.102.168.221
        - ipv4: 34.102.220.13
        - ipv4: 34.102.190.179
        - ipv4: 34.102.233.224
        - ipv4: 34.117.95.95
        - ipv4: 34.160.140.40
        - ipv4: 34.111.181.219
        - ipv4: 34.111.150.233
        - ipv4: 34.107.216.191
        - ipv4: 34.102.242.91
        - ipv4: 35.201.85.63
        - ipv4: 35.190.90.94
        - ipv4: 34.117.92.90
        - ipv4: 34.149.250.58
        - ipv4: 34.160.166.218
        - ipv4: 34.160.171.86
        - ipv4: 34.36.58.112
        - ipv4: 34.117.0.159
        - ipv4: 34.117.101.53
        - ipv4: 34.49.170.196
        - ipv4: 34.49.206.188
        - ipv4: 35.201.69.243
        - ipv4: 34.149.200.141
        - ipv4: 34.98.114.57
        - ipv4: 34.36.101.172
        - ipv4: 34.49.15.205
        - ipv4: 34.117.26.18
        - ipv4: 34.95.108.139
        - ipv4: 34.49.19.79
        - ipv4: 34.49.99.193
        - ipv4: 34.110.228.169
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 2048Mi
      cpu: 250m
  ingresses:
    - https://familie-ks-sak.intern.nav.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod

    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  kafka:
    pool: nav-prod
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
