#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n teamfamilie get secret azuread-familie-ks-sak-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-ks-sak-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  preAuthorizedApplications:
    - application: familie-ks-sak-frontend-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: ida
      cluster: prod-fss
      namespace: traktor
  tenant: trygdeetaten.no
  secretName: azuread-familie-ks-sak-lokal
  claims:
    groups:
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
      - id: "71f503a2-c28f-4394-a05a-8da263ceca4a"  # VEILEDER_ROLLE
      - id: "c7e0b108-7ae6-432c-9ab4-946174c240c0"  # SAKSBEHANDLER_ROLLE
      - id: "52fe1bef-224f-49df-a40a-29f92d4520f8"  # BESLUTTER_ROLLE
  replyUrls:
    - url: "http://localhost:8083/swagger-ui/oauth2-redirect.html"
  singlePageApplication: true