kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: familie-ks-kafka-manager
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2023.08.02-07.02-45dfb71 # See https://github.com/navikt/kafka-manager/packages
  port: 8080
  ingresses:
    - https://familie-ks-kafka-manager.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # forvaltning
  kafka: # Optional. Required for Aiven
    pool: nav-prod
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "teamfamilie.aapen-kontantstotte-vedtak-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-kontantstotte-saksstatistikk-sak-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-kontantstotte-saksstatistikk-behandling-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "alf.aapen-altinn-barnehageliste-mottatt",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }