apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: familie-ks-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamfamilie
  secretName: familie-ks-sak-unleash-api-token
  environment: production