apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-kontantstotte-barnehagelister
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168 # -1 means unlimited
  acl:
    - team: teamfamilie
      application: familie-ks-barnehagelister #owner
      access: write   # readwrite
    - team: teamfamilie
      application: familie-ks-sak
      access: read
    - team: teamfamilie
      application: familie-baks-kafka-manager
      access: read