apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-kontantstotte-saksstatistikk-behandling-v1
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168 # -1 means unlimited
  acl:
    - team: teamfamilie
      application: familie-ks-sak #owner
      access: write   # readwrite
    - team: teamfamilie
      application: familie-baks-kafka-manager
      access: read
    - team: dv-familie
      application: dvh-fambt-konsumer
      access: read
    - team: ptsak
      application: pt-sak-kontantstotte-dev
      access: read
    - team: ptsak
      application: pt-sak-kontantstotte-preprod
      access: read