CREATE TABLE ADOPSJON
(
    ID                  BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID    BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FK_AKTOER_ID        VARCHAR(50) REFERENCES AKTOER (AKTOER_ID) ON UPDATE CASCADE NOT NULL,
    ADOPSJONSDATO       TIMESTAMP(3) NOT NULL,

    -- Base entitet felter
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR(20)      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR(512),
    ENDRET_TID       TIMESTAMP(3),
    UNIQUE (FK_AKTOER_ID, FK_BEHANDLING_ID)
);

CREATE SEQUENCE ADOPSJON_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX ADOPSJON_FK_BEHANDLING_ID__IDX ON ADOPSJON (FK_BEHANDLING_ID);
