name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ks-sak:latest
jobs:
  bygg-og-kjor-tester:
    name: Bygg og test
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'gradle'

      - name: Bygg med gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build

  bygg-og-push-til-github:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'gradle'

      - name: Bygg med gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build -x test -x integrationTest -x ktlintCheck

      - name: Generate and output SBOM
        run: ./gradlew cyclonedxBom

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          tag: latest
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          byosbom: build/reports/bom.json
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-til-preprod:
    name: Deploy to dev-gcp
    needs: [ bygg-og-kjor-tester, bygg-og-push-til-github ]
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml
          IMAGE: ${{ needs.bygg-og-push-til-github.outputs.image }}

  deploy-til-prod:
    name: Deploy til prod-gcp
    needs: [ bygg-og-kjor-tester, bygg-og-push-til-github ]
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml
          IMAGE: ${{ needs.bygg-og-push-til-github.outputs.image }}
