name: Pull request
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}
jobs:
  avslutt-andre-workflows-samme-branch:
    name: Avslutt andre workflows på samme branch
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør ktlint sjekk
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew ktlintCheck --no-daemon --full-stacktrace
  enhetstester-integrasjonstester-og-sonar:
    name: Enhetstester, integrasjonstester og sonar
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør enhetstester, integrasjonstester og sonar
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test -Pgithub -Penhetstester -Pintegrasjonstester -i --no-daemon
  verdikjedetesterFeatureToggleOff:
    name: Verdikjedetester m/ feature toggles slått av
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør verdikjedetester m/ feature toggles slått av
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test -Pgithub -Pverdikjedetester -i --no-daemon
  verdikjedetesterFeatureToggleOn:
    name: Verdikjedetester m/ feature toggles slått på
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør verdikjedetester m/ feature toggles slått på
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test -Pgithub -Pverdikjedetester -Pfeaturetoggle -i --no-daemon