name: Pull request
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}
jobs:
  avslutt-andre-workflows-samme-branch:
    name: Avslutt andre workflows på samme branch
    runs-on: ubuntu-latest-8-cores
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: "actions/checkout@v3"
      - name: Ktlint
        run: |
          ./gradlew -Dfile.encoding=UTF-8 ktlintCheck 

  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør enhetstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test 
  integrasjonstester:
    name: Integrasjonstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Kjør integrasjonstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew integrationTest 