name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ks-sak:latest
jobs:
  bygg-og-push-til-github:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'

      - name: Bygg med gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build

      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}
      - name: Skriv ut docker-taggen
        run: echo 'Docker-tag er ${{ github.sha }} ' >> $GITHUB_STEP_SUMMARY

  lag-salsa-proveniens:
    name: Lag salsa proveniens
    needs: bygg-og-push-til-github
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SALSA_CREDENTIALS }}

      - name: Provenance, upload and sign attestation
        uses: nais/salsa@v0.6
        with:
          key: ${{ secrets.SALSA_KMS_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-til-preprod:
    name: Deploy to dev-gcp
    needs: bygg-og-push-til-github
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml

  deploy-til-prod:
    name: Deploy til prod-gcp
    needs: deploy-til-preprod
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml