name: Pull request
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  avslutt-andre-workflows-samme-branch:
    name: Avslutt andre workflows på samme branch
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress antrun:run@ktlint

  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør enhetstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn verify -B --no-transfer-progress --settings .m2/maven-settings.xml --file pom.xml -DexcludedGroups=integrationTest -Pjacoco -DjacocoTestDirectory=UT
      - name: Last opp Jacoco enhetstester rapport
        uses: actions/upload-artifact@v4
        with:
          name: jacocoTestReport
          path: target/jacoco/UT/jacoco.xml
          retention-days: 1
          overwrite: true

  integrasjonstester:
    name: Integrasjonstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør integrasjonstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn verify -B --no-transfer-progress --settings .m2/maven-settings.xml --file pom.xml -Dgroups=integrationTest -Dsurefire.rerunFailingTestsCount=2 -Pjacoco -DjacocoTestDirectory=IT
      - name: Last opp Jacoco integrasjonstester rapport
        uses: actions/upload-artifact@v4
        with:
          name: jacocoIntegrationTestReport
          path: target/jacoco/IT/jacoco.xml
          retention-days: 1
          overwrite: true

  sonar:
    if: github.actor != 'dependabot[bot]'
    name: Sonar
    runs-on: ubuntu-latest-8-cores
    needs: [ enhetstester, integrasjonstester ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Last ned Jacoco UT rapport
        uses: actions/download-artifact@v4
        with:
          name: jacocoUT
          path: jacoco/UT
      - name: Last ned Jacoco IT rapport
        uses: actions/download-artifact@v4
        with:
          name: jacocoIT
          path: jacoco/IT
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Kjør Sonar
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths="jacoco/UT/jacoco.xml,jacoco/IT/jacoco.xml"
