name: Pull request
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  avslutt-andre-workflows-samme-branch:
    name: Avslutt andre workflows på samme branch
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew ktlintCheck

  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Kjør enhetstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test jacocoTestReport
      - name: Last opp Jacoco enhetstester rapport
        uses: actions/upload-artifact@v4
        with:
          name: jacocoTestReport
          path: build/reports/jacoco/test/jacocoTestReport.xml
          retention-days: 1
          overwrite: true
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: Test-rapport
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

  integrasjonstester:
    name: Integrasjonstester
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Kjør integrasjonstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew integrationTest jacocoIntegrationTestReport
      - name: Last opp Jacoco integrasjonstester rapport
        uses: actions/upload-artifact@v4
        with:
          name: jacocoIntegrationTestReport
          path: build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml
          retention-days: 1
          overwrite: true
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: Test-rapport
          path: "**/build/test-results/integrationTest/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

  sonar:
    name: Sonar
    runs-on: ubuntu-latest-8-cores
    needs: [ enhetstester, integrasjonstester ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Last ned Jacoco enhetstester rapport
        uses: actions/download-artifact@v4
        with:
          name: jacocoTestReport
      - name: Last ned Jacoco integrasjonstester rapport
        uses: actions/download-artifact@v4
        with:
          name: jacocoIntegrationTestReport
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Kjør Sonar
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew sonar -D "sonar.coverage.jacoco.xmlReportPaths=jacocoTestReport.xml,jacocoIntegrationTestReport.xml"
