name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ks-sak:latest
jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til preprod-gcp og til prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'
      - name: Bygg med gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build
      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}
      - name: Skriv ut docker-taggen
        run: echo 'Docker-tag er ${{ github.sha }} ' >> $GITHUB_STEP_SUMMARY
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml
