name: Deploy familie-ks-kafka-manager

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy familie-ks-kafka-manager til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka-manager/dev/familie-ks-kafka-manager.yml
      - name: Deploy familie-ks-kafka-manager til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka-manager/prod/familie-ks-kafka-manager.yml